### ISSUE TITLE
Extension stopped working until disabling and reenabling (persisting through restarts)

### ISSUE THREAD

**Issue by JJCUBER** [laurentkempe/GitDiffMargin#460]
## Versions
 - Git Diff Margin version: 3.12.1
 - Visual Studio version: 16.10.2

## What happened

I noticed that the extension had stopped working for me (the sidebar/margin wouldn't show up).  This persisted through restarts of Visual Studio and my computer.

_I found that disabling the extension, restarting VS, reenabling the extension, then restarting VS again **fixed it**._  Thus far, I have not ran into the issue again.

### Steps to Reproduce
Unfortunately, I'm not entirely sure.  I believe that it occurred around the time that Visual Studio automatically updated the extension to 3.12.1 on 8/5/2021.

**Comment by horeaper** [comment]
Found the same problem in 3.12.1 with VS 16.11, fixed with the same way.

**Comment by theglobe** [comment]
I am experiencing this in VS 2015. Disabling and re-enabling does not fix this, neither does Uninstalling and re-installing.

I had documents open when I tried the above, so it seems not to be related to #456.

How can I troubleshoot this?

**Comment by irontoby** [comment]
Same thing has just happened to me with VS 2022 Professional. I had a separate issue which caused me to run a "repair" on the installation. Afterwards, this extension is no longer working in one of my repos. I've tried disabling/re-enabling, uninstalling/reinstalling etc.

At first I also [ran into this issue](https://developercommunity.visualstudio.com/t/Git-Error-after-1714-update/10012565#T-N10014401). I re-cloned my entire git repo which fixed the problem of VS not recognizing the repo but this extension is still not working with that repo.

I tried creating a new solution for a console app in VS and then created an empty local git repo for it, also through VS. This extension didn't work for that solution at first, but after restarting it's working for that solution. It's still not working for the original solution.

So the problem has something to do with the git repo itself. The only other odd thing about this repo I can think of is that I have multiple worktrees configured.

I'm still doing more investigation, but if there's any place where I can see any logging / output for this extension that would probably help!

**Comment by irontoby** [comment]
Update: I re-cloned my repo using Visual Studio instead of the command-line, and the extension worked with that copy. I then updated my Git for Windows to the latest version, re-cloned with CLI and that one worked too.

So it appears to be an issue with a repo that was cloned using an older version of Git. Still not sure what the issue is, but for anyone who has this issue I'd recommend updating your CLI to the latest version and re-cloning your repo to a new location using either the latest CLI or the VS GUI.
