### ISSUE TITLE
Add option to ignore whitespace changes

### ISSUE THREAD

**Issue by RandScullard** [laurentkempe/GitDiffMargin#77]
I would love to be able to toggle whitespace sensitivity on and off in GitDiffMargin. (Equivalent to passing the --ignore-space-change option to git diff.)

When I have changed the indentation of a large block of code, I usually don't want to see the entire block highlighted, just the lines I've materially changed.

**Comment by PavelAgejkin** [comment]
+1

**Comment by ismusidhu** [comment]
+1

**Comment by glconti** [comment]
This is addressed in #116

**Comment by HamRusTal** [comment]
As an alternative to a plain on/off, I'd prefer to be able to still see the whitespace-only changes, yet with another margin color (paler, configurable).
